#!/bin/bash

container_name="fii_tools"

if [[ $1 == "" ]]; then
    echo "Available options:"
    echo "all"
    echo "tests"
    echo "coverage"
    echo "web_scraper"
    echo "web_extractor"
    echo "analyzer"
elif [[ $1 == "all" ]]; then
    echo "Starting containers"
    docker-compose up
elif [[ $1 == "tests" ]]; then
    echo "Running tests"
    docker exec -it "$container_name" bash -c "cd home/dev/fii && pytest tests/"
elif [[ $1 == "coverage" ]]; then
    echo "Coverage"
    docker exec -it "$container_name" bash -c "cd home/dev/fii && coverage run -m pytest tests/ && coverage report -m --fail-under=100"
elif [[ $1 == "web_extractor" ]]; then
    echo "Web extractor"
    docker exec -it "$container_name" bash -c "cd /home/dev/fii/webpage_extractor && python script.py"
elif [[ $1 == "web_scraper" ]]; then
    echo "HTML scraper"
    docker exec -it "$container_name" bash -c "cd /home/dev/fii/web_scraper && python script.py"
elif [[ $1 == "analyzer" ]]; then
    echo "Reports analyzer"
    docker exec -it "$container_name" bash -c "cd /home/dev/fii/analyzer && python script.py"
else
    echo "Unknown option"
fi