#!/bin/bash

container_name="fii_tools"

if [[ $1 == "" ]]; then
    echo "Available options:"
    echo "all"
    echo "tests"
    echo "coverage"
    echo "web_scraper"
    echo "web_extractor"
    echo "organizer"
    echo "stock"
elif [[ $1 == "all" ]]; then
    echo "Starting containers"
    docker-compose up
elif [[ $1 == "tests" ]]; then
    echo "Running tests"
    docker exec -it "$container_name" bash -c "cd fii && pytest tests/ -vv"
elif [[ $1 == "coverage" ]]; then
    echo "Coverage"
    docker exec -it "$container_name" bash -c "cd fii && coverage run -m pytest tests/ && coverage report -m --fail-under=100"
elif [[ $1 == "web_extractor" ]]; then
    echo "Web extractor"
    docker exec -it "$container_name" bash -c "cd fii/webpage_extractor && python script.py"
elif [[ $1 == "web_scraper" ]]; then
    echo "HTML scraper"
    docker exec -it "$container_name" bash -c "cd fii/web_scraper && python script.py"
elif [[ $1 == "organizer" ]]; then
    echo "Reports organizer"
    docker exec -it "$container_name" bash -c "cd fii/organizer && python script.py"
elif [[ $1 == "stock" ]]; then
    echo "Stock data extractor"
    docker exec -it "$container_name" bash -c "cd fii/stock && python script.py"
else
    echo "Unknown option"
fi