#!/bin/bash

echo "Running pre-commit hook"
container_name="fii_extractor"

if docker exec "$container_name" bash -c "cd home/dev/extractor && flake8 ."; then
    exit 0
else
    echo "Fix lint validation"
fi
exit 1